# Generated by Django 3.2 on 2021-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('Вступление', models.TextField()),
                ('Текст', models.TextField()),
                ('date_abbed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_abbed'],
            },
        ),
    ]
